### ISSUE TITLE
additional attributes are ignored for an image when src is defined in footer

### ISSUE THREAD

**Issue by LokiMidgard** [taufik-nurrohman/markdown#1]
In the following sample the second image will not get the width attribute but the resulting html includes `{width='10px'}`
```md
![BILD_ALT_TEXT](http://foo.bar) {width='10px'}

![BILD_ALT_TEXT][2] {width='10px'}

[2]: …
```

Workaround:
You can workaround it by adding the attribute in the footnote

I can use the workaround in my cases (I think) but thought it might interest you.

**Comment by taufik-nurrohman** [comment]
https://github.com/taufik-nurrohman/markdown/commit/ef5cdfa69d0da1de41bef4c484d1a3090ad6055d

**Comment by LokiMidgard** [comment]
Thank you for the fast fix :)
