### ISSUE TITLE
using base64 encoded image urls seem to break when they get too big

### ISSUE THREAD

**Issue by LokiMidgard** [taufik-nurrohman/markdown#2]
I embed some images in my markdown, and at some point html rendering will break and it will not accept the data.
Neitehr inline nor as references syntax below the text

121kb files and smaler seam to work
146kb and bigger did not.

```md
![imasge][1]

![imasge][2]

[1]: data:image/jpeg;base64,/9j/2w…
[2]: data:image/jpeg;base64,/9j/2w…
```

where 1 work and 2 not will render the image followed by 
```
// here is the image

![imasge][2]
[2]: data:image/jpeg;base64,/9j/2w…
```
![image](https://github.com/taufik-nurrohman/markdown/assets/389101/804ceea4-3429-4761-9263-33f1a124b1c3)

Sample files
https://gist.github.com/LokiMidgard/b9c958b560d4d8b7f19090dc17d17321

not sure if php may get problems with the line length, 146kb base64 encodede will have a bunch of chars…

**Comment by taufik-nurrohman** [comment]
Let&rsquo;s see if I can work around with this case.

**Comment by LokiMidgard** [comment]
my current workaround is setting an id instead of the base64 data and replacing it after html was generated

**Comment by taufik-nurrohman** [comment]
What about wrapping the URL in anchor bracket(s)?

~~~ markdown
![image](<data:image/jpeg;base64,...>)
~~~

~~~ markdown
![image][1]

[1]: <data:image/jpeg;base64,...>
~~~

**Comment by LokiMidgard** [comment]
I've tried following:

```
 ![undefined][1] 

[1]: <data:image/jpeg;base64,/9j … QPVWy7H8EkFXqv/2Q==> {height='100%'}
```
and it did not work :(
